title: Abdul Hakim
logo: /assets/profile 2.png
description: Goal-oriented and hard working, seeking to solve problems through data, machine learning and artificial intelligence. Have worked on multiple ML and AI projects using Python and R. Experienced in working as a team and highly adaptable in various working atmospheres, as well as producing outstanding outputs. Proficient using English and Indonesian in professional environments. Always willing to learn and grow as a professional and an individual.
theme: jekyll-theme-minimal
